# Server properties
server:
  port: 8080

spring:
  # Connection to original data
  datasource:
    url: 'jdbc:postgresql://localhost:5533/postgres'
    username: postgres
    password: password
    initialization-mode: always
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

